"""Probe

Revision ID: 1ec1314e063c
Revises: 4df17d51777e
Create Date: 2023-01-28 17:22:19.803056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec1314e063c'
down_revision = '4df17d51777e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('note', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
