"""Probe

Revision ID: 3b21eacb379d
Revises: 480107041c08
Create Date: 2023-01-28 17:23:46.711317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b21eacb379d'
down_revision = '480107041c08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('phone', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'last_name')
    op.drop_column('clients', 'first_name')
    # ### end Alembic commands ###
