"""Probe

Revision ID: 480107041c08
Revises: 1ec1314e063c
Create Date: 2023-01-28 17:23:00.983389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480107041c08'
down_revision = '1ec1314e063c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('note', sa.String(), nullable=True))
    op.drop_column('clients', 'first_name')
    op.drop_column('clients', 'last_name')
    op.drop_column('clients', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone', sa.INTEGER(), nullable=False))
    op.add_column('clients', sa.Column('last_name', sa.VARCHAR(), nullable=False))
    op.add_column('clients', sa.Column('first_name', sa.VARCHAR(), nullable=False))
    op.drop_column('clients', 'note')
    # ### end Alembic commands ###
